import type { Metadata } from "next";
import "./main.css";
import Introduction from "./Header-Introtuction/Header_Introduction";
import FooterActions from "./FooterActions/FooterActions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gray-100 bg-gradient-to-b from-slate-300 to-slate-300">
          
          <header className="flex justify-center items-center text-black">
            <div className="bg-white p-6 rounded-lg shadow-md w-full max-w-[46rem] mt-8 responsive">
              <Introduction />
            </div>
          </header>

          <main className="flex justify-center items-center min-h-screen text-black">
            {children}
          </main>

          <footer className="flex justify-center items-center text-black">
            <FooterActions />
          </footer>
        </div>
      </body>
    </html>
  );
}
